/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CoordinationCreditsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "balances"
      | "burnDelay"
      | "cancelBurn"
      | "canonical8004"
      | "executeBurn"
      | "gameAnchor"
      | "mint"
      | "mintFor"
      | "pendingBurns"
      | "registry"
      | "requestBurn"
      | "setBurnDelay"
      | "settleDeltas"
      | "transfer"
      | "transferFrom"
      | "treasury"
      | "usdc"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BurnCancelled"
      | "BurnDelayUpdated"
      | "BurnExecuted"
      | "BurnRequested"
      | "CreditsMinted"
      | "CreditsSettled"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "burnDelay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelBurn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canonical8004",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeBurn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameAnchor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintFor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingBurns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestBurn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBurnDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleDeltas",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnDelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBurn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canonical8004",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameAnchor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingBurns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBurnDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleDeltas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace BurnCancelledEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnDelayUpdatedEvent {
  export type InputTuple = [newDelay: BigNumberish];
  export type OutputTuple = [newDelay: bigint];
  export interface OutputObject {
    newDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnExecutedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    credits: BigNumberish,
    usdcAmount: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    credits: bigint,
    usdcAmount: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    credits: bigint;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnRequestedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    amount: BigNumberish,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    amount: bigint,
    executeAfter: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    amount: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsMintedEvent {
  export type InputTuple = [agentId: BigNumberish, credits: BigNumberish];
  export type OutputTuple = [agentId: bigint, credits: bigint];
  export interface OutputObject {
    agentId: bigint;
    credits: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsSettledEvent {
  export type InputTuple = [agentIds: BigNumberish[], deltas: BigNumberish[]];
  export type OutputTuple = [agentIds: bigint[], deltas: bigint[]];
  export interface OutputObject {
    agentIds: bigint[];
    deltas: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoordinationCredits extends BaseContract {
  connect(runner?: ContractRunner | null): CoordinationCredits;
  waitForDeployment(): Promise<this>;

  interface: CoordinationCreditsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  balances: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  burnDelay: TypedContractMethod<[], [bigint], "view">;

  cancelBurn: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  canonical8004: TypedContractMethod<[], [string], "view">;

  executeBurn: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameAnchor: TypedContractMethod<[], [string], "view">;

  mint: TypedContractMethod<
    [agentId: BigNumberish, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintFor: TypedContractMethod<
    [agentId: BigNumberish, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  pendingBurns: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { amount: bigint; executeAfter: bigint }],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  requestBurn: TypedContractMethod<
    [agentId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBurnDelay: TypedContractMethod<
    [newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleDeltas: TypedContractMethod<
    [agentIds: BigNumberish[], deltas: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  transfer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelBurn"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canonical8004"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeBurn"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameAnchor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [agentId: BigNumberish, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintFor"
  ): TypedContractMethod<
    [agentId: BigNumberish, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingBurns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { amount: bigint; executeAfter: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestBurn"
  ): TypedContractMethod<
    [agentId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBurnDelay"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleDeltas"
  ): TypedContractMethod<
    [agentIds: BigNumberish[], deltas: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BurnCancelled"
  ): TypedContractEvent<
    BurnCancelledEvent.InputTuple,
    BurnCancelledEvent.OutputTuple,
    BurnCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BurnDelayUpdated"
  ): TypedContractEvent<
    BurnDelayUpdatedEvent.InputTuple,
    BurnDelayUpdatedEvent.OutputTuple,
    BurnDelayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BurnExecuted"
  ): TypedContractEvent<
    BurnExecutedEvent.InputTuple,
    BurnExecutedEvent.OutputTuple,
    BurnExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BurnRequested"
  ): TypedContractEvent<
    BurnRequestedEvent.InputTuple,
    BurnRequestedEvent.OutputTuple,
    BurnRequestedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsMinted"
  ): TypedContractEvent<
    CreditsMintedEvent.InputTuple,
    CreditsMintedEvent.OutputTuple,
    CreditsMintedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsSettled"
  ): TypedContractEvent<
    CreditsSettledEvent.InputTuple,
    CreditsSettledEvent.OutputTuple,
    CreditsSettledEvent.OutputObject
  >;

  filters: {
    "BurnCancelled(uint256)": TypedContractEvent<
      BurnCancelledEvent.InputTuple,
      BurnCancelledEvent.OutputTuple,
      BurnCancelledEvent.OutputObject
    >;
    BurnCancelled: TypedContractEvent<
      BurnCancelledEvent.InputTuple,
      BurnCancelledEvent.OutputTuple,
      BurnCancelledEvent.OutputObject
    >;

    "BurnDelayUpdated(uint256)": TypedContractEvent<
      BurnDelayUpdatedEvent.InputTuple,
      BurnDelayUpdatedEvent.OutputTuple,
      BurnDelayUpdatedEvent.OutputObject
    >;
    BurnDelayUpdated: TypedContractEvent<
      BurnDelayUpdatedEvent.InputTuple,
      BurnDelayUpdatedEvent.OutputTuple,
      BurnDelayUpdatedEvent.OutputObject
    >;

    "BurnExecuted(uint256,uint256,uint256)": TypedContractEvent<
      BurnExecutedEvent.InputTuple,
      BurnExecutedEvent.OutputTuple,
      BurnExecutedEvent.OutputObject
    >;
    BurnExecuted: TypedContractEvent<
      BurnExecutedEvent.InputTuple,
      BurnExecutedEvent.OutputTuple,
      BurnExecutedEvent.OutputObject
    >;

    "BurnRequested(uint256,uint256,uint256)": TypedContractEvent<
      BurnRequestedEvent.InputTuple,
      BurnRequestedEvent.OutputTuple,
      BurnRequestedEvent.OutputObject
    >;
    BurnRequested: TypedContractEvent<
      BurnRequestedEvent.InputTuple,
      BurnRequestedEvent.OutputTuple,
      BurnRequestedEvent.OutputObject
    >;

    "CreditsMinted(uint256,uint256)": TypedContractEvent<
      CreditsMintedEvent.InputTuple,
      CreditsMintedEvent.OutputTuple,
      CreditsMintedEvent.OutputObject
    >;
    CreditsMinted: TypedContractEvent<
      CreditsMintedEvent.InputTuple,
      CreditsMintedEvent.OutputTuple,
      CreditsMintedEvent.OutputObject
    >;

    "CreditsSettled(uint256[],int256[])": TypedContractEvent<
      CreditsSettledEvent.InputTuple,
      CreditsSettledEvent.OutputTuple,
      CreditsSettledEvent.OutputObject
    >;
    CreditsSettled: TypedContractEvent<
      CreditsSettledEvent.InputTuple,
      CreditsSettledEvent.OutputTuple,
      CreditsSettledEvent.OutputObject
    >;
  };
}
