/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CoordinationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canonical8004"
      | "checkName"
      | "creditContract"
      | "displayName"
      | "nameToAgent"
      | "registerExisting"
      | "registerNew"
      | "registered"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;

  encodeFunctionData(
    functionFragment: "canonical8004",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "checkName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "creditContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "displayName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nameToAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerExisting",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNew",
    values: [string, string, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "canonical8004",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "displayName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nameToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerExisting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registered", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace RegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    agentId: BigNumberish,
    name: string
  ];
  export type OutputTuple = [user: string, agentId: bigint, name: string];
  export interface OutputObject {
    user: string;
    agentId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoordinationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CoordinationRegistry;
  waitForDeployment(): Promise<this>;

  interface: CoordinationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canonical8004: TypedContractMethod<[], [string], "view">;

  checkName: TypedContractMethod<[name: string], [boolean], "view">;

  creditContract: TypedContractMethod<[], [string], "view">;

  displayName: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  nameToAgent: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  registerExisting: TypedContractMethod<
    [
      name: string,
      agentId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registerNew: TypedContractMethod<
    [
      name: string,
      agentURI: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registered: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canonical8004"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkName"
  ): TypedContractMethod<[name: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "creditContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "displayName"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "nameToAgent"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerExisting"
  ): TypedContractMethod<
    [
      name: string,
      agentId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerNew"
  ): TypedContractMethod<
    [
      name: string,
      agentURI: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registered"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;

  filters: {
    "Registered(address,uint256,string)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
  };
}
