/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GameAnchor {
  export type GameResultStruct = {
    gameId: BytesLike;
    gameType: string;
    players: BigNumberish[];
    outcome: BytesLike;
    movesRoot: BytesLike;
    configHash: BytesLike;
    turnCount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type GameResultStructOutput = [
    gameId: string,
    gameType: string,
    players: bigint[],
    outcome: string,
    movesRoot: string,
    configHash: string,
    turnCount: bigint,
    timestamp: bigint
  ] & {
    gameId: string;
    gameType: string;
    players: bigint[];
    outcome: string;
    movesRoot: string;
    configHash: string;
    turnCount: bigint;
    timestamp: bigint;
  };
}

export interface GameAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "credits"
      | "emergencyReclaim"
      | "reclaimDelay"
      | "relayer"
      | "results"
      | "setReclaimDelay"
      | "settleGame"
      | "settled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyReclaimed"
      | "GameSettled"
      | "ReclaimDelayUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "credits", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyReclaim",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimDelay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(functionFragment: "results", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setReclaimDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleGame",
    values: [GameAnchor.GameResultStruct, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "settled", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "credits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyReclaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reclaimDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReclaimDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settled", data: BytesLike): Result;
}

export namespace EmergencyReclaimedEvent {
  export type InputTuple = [gameId: BytesLike];
  export type OutputTuple = [gameId: string];
  export interface OutputObject {
    gameId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameSettledEvent {
  export type InputTuple = [
    gameId: BytesLike,
    movesRoot: BytesLike,
    players: BigNumberish[],
    deltas: BigNumberish[]
  ];
  export type OutputTuple = [
    gameId: string,
    movesRoot: string,
    players: bigint[],
    deltas: bigint[]
  ];
  export interface OutputObject {
    gameId: string;
    movesRoot: string;
    players: bigint[];
    deltas: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReclaimDelayUpdatedEvent {
  export type InputTuple = [newDelay: BigNumberish];
  export type OutputTuple = [newDelay: bigint];
  export interface OutputObject {
    newDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): GameAnchor;
  waitForDeployment(): Promise<this>;

  interface: GameAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  credits: TypedContractMethod<[], [string], "view">;

  emergencyReclaim: TypedContractMethod<
    [gameId: BytesLike],
    [void],
    "nonpayable"
  >;

  reclaimDelay: TypedContractMethod<[], [bigint], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  results: TypedContractMethod<
    [gameId: BytesLike],
    [GameAnchor.GameResultStructOutput],
    "view"
  >;

  setReclaimDelay: TypedContractMethod<
    [newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleGame: TypedContractMethod<
    [result: GameAnchor.GameResultStruct, deltas: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  settled: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "credits"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyReclaim"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reclaimDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [gameId: BytesLike],
    [GameAnchor.GameResultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "setReclaimDelay"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleGame"
  ): TypedContractMethod<
    [result: GameAnchor.GameResultStruct, deltas: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settled"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "EmergencyReclaimed"
  ): TypedContractEvent<
    EmergencyReclaimedEvent.InputTuple,
    EmergencyReclaimedEvent.OutputTuple,
    EmergencyReclaimedEvent.OutputObject
  >;
  getEvent(
    key: "GameSettled"
  ): TypedContractEvent<
    GameSettledEvent.InputTuple,
    GameSettledEvent.OutputTuple,
    GameSettledEvent.OutputObject
  >;
  getEvent(
    key: "ReclaimDelayUpdated"
  ): TypedContractEvent<
    ReclaimDelayUpdatedEvent.InputTuple,
    ReclaimDelayUpdatedEvent.OutputTuple,
    ReclaimDelayUpdatedEvent.OutputObject
  >;

  filters: {
    "EmergencyReclaimed(bytes32)": TypedContractEvent<
      EmergencyReclaimedEvent.InputTuple,
      EmergencyReclaimedEvent.OutputTuple,
      EmergencyReclaimedEvent.OutputObject
    >;
    EmergencyReclaimed: TypedContractEvent<
      EmergencyReclaimedEvent.InputTuple,
      EmergencyReclaimedEvent.OutputTuple,
      EmergencyReclaimedEvent.OutputObject
    >;

    "GameSettled(bytes32,bytes32,uint256[],int256[])": TypedContractEvent<
      GameSettledEvent.InputTuple,
      GameSettledEvent.OutputTuple,
      GameSettledEvent.OutputObject
    >;
    GameSettled: TypedContractEvent<
      GameSettledEvent.InputTuple,
      GameSettledEvent.OutputTuple,
      GameSettledEvent.OutputObject
    >;

    "ReclaimDelayUpdated(uint256)": TypedContractEvent<
      ReclaimDelayUpdatedEvent.InputTuple,
      ReclaimDelayUpdatedEvent.OutputTuple,
      ReclaimDelayUpdatedEvent.OutputObject
    >;
    ReclaimDelayUpdated: TypedContractEvent<
      ReclaimDelayUpdatedEvent.InputTuple,
      ReclaimDelayUpdatedEvent.OutputTuple,
      ReclaimDelayUpdatedEvent.OutputObject
    >;
  };
}
