/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { CoordinationCredits } from "./CoordinationCredits";
export type { CoordinationRegistry } from "./CoordinationRegistry";
export type { GameAnchor } from "./GameAnchor";
