/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC8004__factory } from "./MockERC8004__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
