/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoordinationCredits,
  ICoordinationCreditsInterface,
} from "../../../contracts/interfaces/ICoordinationCredits";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "usdcAmount",
        type: "uint256",
      },
    ],
    name: "mintFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "agentIds",
        type: "uint256[]",
      },
      {
        internalType: "int256[]",
        name: "deltas",
        type: "int256[]",
      },
    ],
    name: "settleDeltas",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICoordinationCredits__factory {
  static readonly abi = _abi;
  static createInterface(): ICoordinationCreditsInterface {
    return new Interface(_abi) as ICoordinationCreditsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICoordinationCredits {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICoordinationCredits;
  }
}
