/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { CoordinationCredits__factory } from "./CoordinationCredits__factory";
export { CoordinationRegistry__factory } from "./CoordinationRegistry__factory";
export { GameAnchor__factory } from "./GameAnchor__factory";
